### ISSUE TITLE
not suppoert vite 4.4.5?

### ISSUE THREAD

**Issue by ywzhaiqi** [nonzzz/vite-plugin-cdn#17]
```bash
> set DEBUG=vite-plugin-cdn2 && vite build

  vite-plugin-cdn2 start scanning +0ms
  vite-plugin-cdn2 scanning done Map(0) {} +337ms
vite-plugin-cdn2: vue __require.resolve is not a function
vite v4.4.5 building for production...
```

mini demo: https://codesandbox.io/p/sandbox/vite-plugin-cdn2-not-work-s6p78h

**Comment by nonzzz** [comment]
It's seems like `require.resolve` can't process right esm code caused. I check the codesandbox. I will create a new patch version.

**Comment by nonzzz** [comment]
`0.9.3` has been released. Bump the version can work  @ywzhaiqi
