### ISSUE TITLE
[vite-plugin-cdn] Cannot read properties of undefined (reading 'id')   

### ISSUE THREAD

**Issue by ersb-cn** [nonzzz/vite-plugin-cdn#23]
vite 4,Vue3
![image](https://github.com/nonzzz/vite-plugin-cdn/assets/84365910/7cd6e155-4cbd-4d3b-b1e5-e5439ceef13b)

**Comment by nonzzz** [comment]
Full conf. Have you using `unplugin-vue-component` or `unplugin-auto-import`?

**Comment by nonzzz** [comment]
`element-plus` depends on `vue-demi`. try add `vue-demi` in modules

**Comment by nonzzz** [comment]
BTW. I think it's a bug for code-gen. I'll create a fix version

**Comment by nonzzz** [comment]
Released `0.12.3` . If you find problem. Please reopen

**Comment by nonzzz** [comment]
Latest. we release `0.12.4` and `0.12.3` be deserted.
