### ISSUE TITLE
element-plus问题

### ISSUE THREAD

**Issue by jian-jiu** [nonzzz/vite-plugin-cdn#24]
modules 中排除 element-plus 后打包结果存在 element-plus@2.3.12_vue@3.3.4/node_modules/element-plus 如何解决？

**Comment by nonzzz** [comment]
请提供配置 以及chunk产物

**Comment by jian-jiu** [comment]
```js
cdn({
    url: 'https://unpkg.com',
    modules: [
      'vue',
      'vue-demi',
      'vue-router',
      { name: 'element-plus', relativeModule: 'dist/index.full.min.js' },
      '@element-plus/icons-vue'
    ]
  })
```

![image](https://github.com/nonzzz/vite-plugin-cdn/assets/65639336/2de9355e-b115-4cce-bcba-054c0852b45c)

**Comment by nonzzz** [comment]
> ```js
> cdn({
>     url: 'https://unpkg.com',
>     modules: [
>       'vue',
>       'vue-demi',
>       'vue-router',
>       { name: 'element-plus', relativeModule: 'dist/index.full.min.js' },
>       '@element-plus/icons-vue'
>     ]
>   })
> ```
> 
> ![image](https://user-images.githubusercontent.com/65639336/267593226-2de9355e-b115-4cce-bcba-054c0852b45c.png)

[Q&A](https://github.com/nonzzz/vite-plugin-cdn/blob/master/docs/Q%26A.md)

**Comment by jian-jiu** [comment]
添加 aliases: ['es'] 后解决完毕
