### ISSUE TITLE
axios问题

### ISSUE THREAD

**Issue by jian-jiu** [nonzzz/vite-plugin-cdn#25]
升级0.12.3版本后错误，0.12.2没有问题
![image](https://github.com/nonzzz/vite-plugin-cdn/assets/65639336/69314df2-d0f0-4409-864e-6d4ce73ae913)

**Comment by nonzzz** [comment]
#23 导致的一个问题。

**Comment by jian-jiu** [comment]
？？？不明白，要如何解决。0.12.2不是很正常吗

**Comment by nonzzz** [comment]
会在0.12.4进行修复。

**Comment by jian-jiu** [comment]
完美！
