### ISSUE TITLE
Package subpath './es/components/button/style/css' is not defined by "exports" in D:\cdn\node_modules\element-plus\package.json

### ISSUE THREAD

**Issue by luboxy** [nonzzz/vite-plugin-cdn#29]
自己封装组件库，引用了element-plus，用的unplugin-element-plus自动导入样式，代码编译后，里面有相关代码
```ts
import { ElButton } from 'element-plus'
import 'element-plus/es/components/button/style/css'
```
![图片](https://github.com/nonzzz/vite-plugin-cdn/assets/21299398/fc667950-893d-4ed3-a9e4-b5647038665b)

cdn插件modules加入自己组件，就会报错。

跟踪代码发现是 _import 执行的时候报的这个错误。
重现步骤：
创建一个vite项目，新建 test.cjs 文件，内容如下：
```ts
var elementPlus = require('element-plus');
require('element-plus/es/components/button/style/css');
exports.ElButton = elementPlus.ElButton
```

vite.config.ts 文件里面添加以下代码：
``` ts
import url from "url";
const modulePath = url.pathToFileURL(
  "D:\\cdn\\test.cjs"
);
const _import = new Function("specifier", "return import(specifier)");
const pkg  = await _import(modulePath);
```

运行就会报错：Package subpath './es/components/button/style/css' is not defined by "exports"...

![图片](https://github.com/nonzzz/vite-plugin-cdn/assets/21299398/4f7efa44-0748-4403-85e6-f6508996e55d)

**删除 require('element-plus/es/components/button/style/css')就正常了。**

**Comment by nonzzz** [comment]
能提供一下cdn的配置嘛

**Comment by nonzzz** [comment]
`_import`的逻辑是在`getPackageExports`里面执行的而这个方法只会在`buildStart`阶段执行。不会发生在`transform`。我需要得到具体的配置信息

**Comment by nonzzz** [comment]
![image](https://github.com/nonzzz/vite-plugin-cdn/assets/52351095/92990a3a-e033-4e7d-8e88-15ccb181fcc2)
这是我用`vite-plugin-inspect`得到的结果。他正常工作

**Comment by luboxy** [comment]
unplugin-element-plus：0.4.0
vite-plugin-cdn2：0.13.0
```ts
 cdn({
      url: "//unpkg.com",
      modules: [
        "vue",
        { name: "element-plus" },
        { name: "sh-ui", global: "ShUi" },
      ],
      resolve: (base, { name, version }) => {
        if (name === "vue" || name === "vue-router") {
          return `${base}/${name}/dist/${name}.global.prod.js`;
        } else if (name === "element-plus") {
          return `${base}/${name}@${version}/dist/index.full.min.js`;
        }else {
          return `http://localhost/sh-ui/index.full.js`;
        }
      }
    })
```
就是 import报错了，没有进到resolve里面呢 ，sh-ui那个，只有vue和element进了resolve。

你安装我这个包，试一下看看，就会报错了，pnpm add ./sh-ui-0.0.1.tgz  

[sh-ui-0.0.1.tgz](https://github.com/nonzzz/vite-plugin-cdn/files/13296373/sh-ui-0.0.1.tgz)

**Comment by luboxy** [comment]
生成的只有两个地址，sh-ui那个就报错了没有生成。
![图片](https://github.com/nonzzz/vite-plugin-cdn/assets/21299398/ad2a2af3-1892-48a9-b03b-09e483143374)

**Comment by nonzzz** [comment]
我知道为什么了。 引入你引入了css文件但是`import`是无法处理非js文件的。这里我会换个loader方式去解决它

**Comment by nonzzz** [comment]
通过查看bundle产物
![image](https://github.com/nonzzz/vite-plugin-cdn/assets/52351095/6c2269cf-d0ff-4993-9cdd-b5dcaf5dc948)
这些完全是不符合预期的。 你可以提供一个类似于style的文件夹存放他们。要么内联成css字符串。

**Comment by nonzzz** [comment]
除非 nodejs 提供 esm版本的`require.extension` 。

**Comment by luboxy** [comment]
是公司内部的业务组件库，依赖了很多第三方的库，不引入CSS就没问题 js里面，我单独处理一下css，独立出来。多谢了。

**Comment by nonzzz** [comment]
其实业务组件库内部的话完全可以外部化vue就够了。剩下的内容这个插件也能正常处理
