### ISSUE TITLE
highlight.js 编译失败

### ISSUE THREAD

**Issue by jim3ma** [nonzzz/vite-plugin-cdn#31]
首先感谢作者的无私奉献。

请教一下关于如何加载 `highlight.js`

```
      modules: [
        'vue',
        'highlight.js',
      ...
```

错误日志：

```
vite-plugin-cdn2: highlight.js try resolve file failed.
```

**Comment by nonzzz** [comment]
参考 [highlight.js](https://github.com/highlightjs/highlight.js/blob/main/README.CDN.md). 同时你需要自己手动指定`highlight.js`的globalName.因为这个包十分怪异。同时你也需要指定`relativeModule`字段随你自己的想法来。然后为了保险起见得在`transform`这个hook里面手动调整为正确的cdn地址。

**Comment by jim3ma** [comment]
第一次用，对 globalName 和 relativeModule 不是很理解， transform 有看到例子

**Comment by nonzzz** [comment]
modules:[ {name:'highlight.js',global:'hljs',relativeModule:''} ]

**Comment by nonzzz** [comment]
@jim3ma `relativeModule` 有2个用处一个是当包没提供对应`umd`或者`iife`模块的时候读取这个地址然后推测`globalName`。然后作为cdn地址加入到`html`里面。这里要传入任意`relativeModule`是因为`highlight.js`并没有提供。但是插件是需要依据包有没有`umd`或者`iife`模块进行进一步判断。因此你同时需要在`transform`这个hook里面拿到`highlight.js`相关的url。并且重写他们

**Comment by jim3ma** [comment]
好的，非常感谢，我大概理解了，去尝试一下

**Comment by nonzzz** [comment]
具体可以参照 [scanner.ts](https://github.com/nonzzz/vite-plugin-cdn/blob/master/src/scanner.ts#L122-L130) 和 [inject.ts](https://github.com/nonzzz/vite-plugin-cdn/blob/master/src/inject.ts#L22C10-L28)。 因为从我的角度来看如果一个库不提供`iife`或者`umd`包的话他是无法进行external的除非使用esm的`importMap`。但是目前我觉得`importMap`还存在很多不足所以是这么实现的

**Comment by jim3ma** [comment]
确实如此，没有提供 iife 和 umd 不好搞
