### ISSUE TITLE
希望增加备用方案

### ISSUE THREAD

**Issue by jian-jiu** [nonzzz/vite-plugin-cdn#33]
由于cdn可能存在访问失败的问题。

希望增加备用方案。
通过属性配置是否开启 开启后不会排除使用了cdn的资源
并且 如果cdn超时未加载成功。还是使用项目资源进行加载

不知道方案是否可行

**Comment by nonzzz** [comment]
关于fallback的这个问题我觉得是需要考虑的

- CDN失效的情况极低(选用稳定的CDN源。做好容灾的情况下概率太低了)
- fallback bundle chunk的话 得额外针对external的模块做单独的打包 然后在html里面inject这些chunk(如果发生了net err) 关于这一点我觉得目前是没有足够的理由去支持他。

**Comment by jian-jiu** [comment]
目前我认为最好用最全的cdn是unpkg以及jsdelivr，但是这两个网站都不属于cn的，国内cdn似乎没有这些cdn全面。
我目前在做zf项目，有些部门出现了访问这两个网站一直无数据包返回。访问cn境内cdn没有问题。
如果有fallback方案当然是最好的（在不影响当前功能情况下的话）
关于你的第二点，前面我可以理解。后面是什么意思【然后在html里面inject这些chunk(如果发生了net err) 关于这一点我觉得目前是没有足够的理由去支持他。】

**Comment by jian-jiu** [comment]
国内的cdn并不是很全。
增加备用方案如果工程量很大的话。那可能确实没必要了
目前我是把cdn关了。不然zf那边三天两头过来说访问不了。想要知道原因还是很麻烦的。要远程过去看才知道
如果有备用的方案。我还是很乐意把cdn重新打开

**Comment by staoran** [comment]
https://npmmirror.com/
这个 cn 源很全
