### ISSUE TITLE
cdnjs.com 引入错误

### ISSUE THREAD

**Issue by Mt-Youya** [nonzzz/vite-plugin-cdn#35]
```js
  cdn({
                modules: ["react","axios"],
                url: "https://cdnjs.cloudflare.com/ajax/libs/",
 }),
// 404
```

**Comment by Mt-Youya** [comment]
[cdnjs](https://cdnjs.com)

**Comment by Mt-Youya** [comment]
> 

404 还要什么错误?
GET https://cdnjs.cloudflare.com/ajax/libs/xlsx@0.18.5/dist/xlsx.full.min.js net::ERR_ABORTED 404 (Not Found)
GET https://cdnjs.cloudflare.com/ajax/libs/axios@1.5.1/dist/axios.min.js net::ERR_ABORTED 404 (Not Found)


✅ https://cdnjs.cloudflare.com/ajax/libs/axios/1.6.2/axios.min.js
❌https://cdnjs.cloudflare.com/ajax/libs/axios@1.5.1/dist/axios.min.js

**Comment by nonzzz** [comment]
看起来像是解析出的URL不对。有尝试使用过`resolve` 和`transform` 选项吗？

**Comment by Mt-Youya** [comment]
> 看起来像是解析出的URL不对。有尝试使用过`resolve` 和`transform` 选项吗？

没有,我去试试

**Comment by Mt-Youya** [comment]
看不懂 resolve 和transform 怎么用

**Comment by nonzzz** [comment]
`transform`是一个钩子可以拿到最后转换的结果然后你访问script节点修改节点对应的url就行

**Comment by nonzzz** [comment]
你如果不会配置可以升级到`1.0.0`版本这是一个稳定版本同时废弃了transform和url 采用resolve的方式 就行。

```js

import { cdnjs } from 'vite-plugin-cdn2/resolver/cdnjs'
import { cdn } from 'vite-plugin-cdn2'

cdn({
 modules:[],
 resolve: cdnjs()

})

```

**Comment by Mt-Youya** [comment]
[cdn-demo](https://github.com/Mt-Youya/cdn-demo)
我新建了个demo,github拉你了

**Comment by Mt-Youya** [comment]
npm run build
pnpm build
都会报错 :  
vite-plugin-cdn2: react-dom try resolve file failed.
vite-plugin-cdn2: react try resolve file failed.

**Comment by nonzzz** [comment]
<img width="1062" alt="image" src="https://github.com/nonzzz/vite-plugin-cdn/assets/52351095/6cafd58d-0630-4959-b184-5a6b0f1aea5a">

**Comment by nonzzz** [comment]
https://github.com/nonzzz/vite-plugin-cdn/blob/master/docs/Q%26A.md

**Comment by Mt-Youya** [comment]
okay了
