### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Awxm** [nonzzz/vite-plugin-cdn#39]
配置：    cdn({
        modules: [
          { name: 'axios', relativeModule: './axios.min.js' },
          { name: 'element-ui', relativeModule: './element-ui.min.js', aliases: ['client'] },
        ],
        resolve: {
          name: 'resolve:cdnjs',
          setup({ extra }) {
            const baseURL = 'https://cdnjs.cloudflare.com/ajax/libs/';
            const { version, name, relativeModule } = extra;
            console.log(relativeModule);
            const url = new URL(`${name}/${version}/${relativeModule}`, baseURL);
            console.log(url);
            return {
              url: url.href,
              injectTo: 'head-prepend',
              attrs: {},
            };
          },
        },
      }),

 ERROR  vite-plugin-cdn2: axios Maximum call stack size exceeded                    
 ERROR  vite-plugin-cdn2: element-ui Maximum call stack size exceeded 
 我在vue2的版本上使用然后报错了 是我的配置不对吗

**Comment by nonzzz** [comment]
请不要提重复issue
