### ISSUE TITLE
打包报错

### ISSUE THREAD

**Issue by pengyinghao** [nonzzz/vite-plugin-cdn#5]
这个错怎么解决呢
<img width="1211" alt="image" src="https://user-images.githubusercontent.com/34115313/221159984-8fb3c788-931c-4f3f-997e-5bac31cc10b4.png">
<img width="885" alt="image" src="https://user-images.githubusercontent.com/34115313/221160009-4feac522-70ad-4437-8d86-f2cfc481ec9e.png">

**Comment by mlzzen** [comment]
来个最简复现的demo

**Comment by pengyinghao** [comment]
[demo.zip](https://github.com/nonzzz/vite-plugin-cdn/files/10837243/demo.zip)

**Comment by pengyinghao** [comment]
> 来个最简复现的demo
[demo.zip](https://github.com/nonzzz/vite-plugin-cdn/files/10837250/demo.zip)

**Comment by Jane0220** [comment]
碰到了一样的问题，参考了隔壁库的解决方案解决的

https://github.com/MMF-FE/vite-plugin-cdn-import/issues/13#issuecomment-1000748279

需要先把vue按cdn引入，然后再把vue-demi按cdn方式引入，再处理其它需要cdn引入的库（比如pinia、ui组件库等）

另外由于打包后加载脚本顺序的关系，不能给cdn文件加defer（打包后的文件先是引入了入口文件，然后再是cdn文件，且入口文件也没有defer属性）

**Comment by nonzzz** [comment]
#6
